config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations'
}
  resources :users, only: [:show,:index,:edit,:update] do
  	member do
      get :following, :followers
    end
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  root to: 'home#top'
  get 'home/about' => 'home#about'
  get "search" => "users#search"
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
belongs_to :user
belongs_to :book
validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
 before_action :authenticate_user!
  def create
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
    if @book_comment.save
      flash[:success] = "Comment was successfully created."
      render :index
    else
       @book_comments = BookComment.where(id: @book)
  end
end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.find_by(book_id: @book.id)
    if @book_comment.user != current_user
      redirect_back(fallback_location: root_path)
    end
    @book_comment.destroy
    render :index
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model: [book, book_comment], url: book_book_comments_path(book) ) do |f| %>
<% if @book_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_comment.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% book_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field row">
    <%= f.text_area :comment, class: "col-xs-11 book_body" %>
  </div>
  <div class="actions row">
    <%= f.submit "送信", class: "btn btn-primary col-xs-11" %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
<li class="comment row">
<%= link_to (book_comment.user) do %>
<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
<%= book_comment.user.name %>
<% end %>
<div class="comment-body">
<p class="comment-txt">
<%= book_comment.comment %>
</p>
<% if current_user == book_comment.user %>
<p><%= link_to book_book_comments_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn-sm btn-danger destroy_book_#{book_comment}" do %>
	Destroy
	<% end %>
	</p>
	<% end %>
</div>
</li>
<% end %>

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', { book: @book, book_comment: @book_comment }) %>")
$("textarea").val('')